name: Sync master to repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          # Fetch the full history to allow for accurate diff operations
          # and to ensure all branches and commit history are available.
          fetch-depth: 0

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Check for changes
        id: check_changes
        run: node scripts/check-folder-changes.js

      - name: Use the output
        if: steps.check_changes.outputs.has_changes == 'true'
        run: echo "Changes were detected!"
