name: Sync master to repo

on:
  push:
    branches:
      - main
      - 'pr/**'

jobs:
  sync-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'