name: Sync master to repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.WITH_TEST_OSS }}
        with:
          source-directory: '.'
          destination-github-username: 'anerishah97'
          destination-repository-name: 'test-oss-destination'
          user-email: anerishah97@gmail.com
          target-branch: main
