name: Sync master to repo

on:
  push:
    branches:
      - main
      - 'pr/**'

jobs:
  sync-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to destination repository
        run: |
          git remote add destination git@github.com:anerishah97/test-oss-destination.git
          git push destination ${GITHUB_REF_NAME}:${GITHUB_REF_NAME} --force
