name: Sync master to repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Determine base and head commits
        id: git_info
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Last commit: $(git log -1 --pretty=format:'%H')"
          echo "Previous commit: $(git log -2 --pretty=format:'%H' | tail -n 1)"
          BASE_COMMIT=$(git log -2 --pretty=format:'%H' | tail -n 1)
          HEAD_COMMIT=$(git log -1 --pretty=format:'%H')
          echo "GITHUB_BASE_REF=${BASE_COMMIT}" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF=${HEAD_COMMIT}" >> $GITHUB_ENV
          echo "Debug: GITHUB_BASE_REF=${BASE_COMMIT}"
          echo "Debug: GITHUB_HEAD_REF=${HEAD_COMMIT}"

      - name: Check for changes
        id: check_changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BASE_REF: ${{ env.GITHUB_BASE_REF }}
          GITHUB_HEAD_REF: ${{ env.GITHUB_HEAD_REF }}
        run: node scripts/check-folder-changes.js

      - name: Use the output
        if: steps.check_changes.outputs.has_changes == 'true'
        run: echo "Changes were detected!"
