name: Sync master to repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push to destination repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WITH_TEST_OSS }}
          repository: anerishah97/test-oss-destination
          branch: main
          force: true
